#!/bin/bash

function tg_sendText() {
curl -s "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
-d "parse_mode=html" \
-d text="${1}" \
-d chat_id=$CHAT_ID \
-d "disable_web_page_preview=true"
}

function tg_sendFile() {
curl -F chat_id=$CHAT_ID -F document=@${1} -F parse_mode=markdown https://api.telegram.org/bot$BOT_TOKEN/sendDocument
}

tg_sendText "ccache upload"
cd /tmp

com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf cr_$1.tar.gz $1
}

up(){
	curl --upload-file $1 https://transfer.sh/ | tee download.txt
}


cd /tmp
time com ccache 3 # Compression level 1, its enough
#zip ccache.zip cr_ccache.tar.gz
up cr_ccache.tar.gz
tg_sendFile "download.txt"
cd /tmp/rom

